airboxproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from pages.views import welcome_page
from main_blog import views

urlpatterns = [
    # path('index', welcome_page , name='home'),
    # path('home', welcome_page , name='home'),
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('main_blog/', include('main_blog.urls', namespace='main_blog')),
    re_path('.*', views.main_blog),
]

article/urls.py
from django.urls import path
from article import views

app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
]

main_blog/urls.py
from django.urls import path
from main_blog import views

app_name = 'main_blog'
urlpatterns = [
    path('', views.main_blog, name='main_blog'),
    path('about/', views.about, name='about'),
]

article/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()

    def __str__(self):
        return self.title

    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=128)
    
    def __str__(self):
        return self.article.title + '-' + str(self.id)
        
        

main_blog/models.py
from django.db import models

# Create your models here.

article/views.py
from django.shortcuts import render

# Create your views here.
def article(request):
    return render(request, 'article/article.html')

main_blog/views.py
from django.shortcuts import render
# from django.http import HttpResponse

# Create your views here.
def main_blog(request):
    context = {'x': 10, 'y': 20}
    return render(request, 'main_blog/my_blog.html', context)

def about(request):
    return render (request, 'main_blog/about.html')

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def welcome_page(request):
    return render(request, 'base.html')

article/templates/article/article.html
{% extends 'main_blog/base.html' %}

{% block heading %}文章{% endblock %}

{% block content %}
<h2>部落格 -- 平凡到超凡的起點</h2>
{% endblock %}

main_blog/templates/main_blog/about.html
{% extends 'main_blog/base.html' %}

{% block heading %}關於{% endblock %}

{% block content %}
<h2>About My Blog !</h2>
<p>Welcome to My Blog</p>
{% endblock %}

main_blog/templates/main_blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main_blog/css/main_blog.css' %}">
    <script src="{% static 'main_blog/js/main_blog.js' %}"></script>
    <title>部落格</title>
</head>
<body>
    {% include 'main_blog/menu.html' %}
    <h2>部落格 -- {% block heading %}{% endblock %}</h2>
    {% block content %}{% endblock %}

    <h3>this is test</h3>
    <p id='demo'><script>add({{ x }},{{ y }} )</script></p>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous">
    </script>

</body>
</html>

main_blog/templates/main_blog/menu.html
<ul id='menu'>
    <li><a href="{% url 'main_blog:main_blog' %}">首頁</a></li>
    <li><a href="{% url 'main_blog:about' %}">關於</a></li>
    <li><a href="{% url 'article:article' %}">部落格</a></li>
</ul>

main_blog/templates/main_blog/my_blog.html
{% extends 'main_blog/base.html' %}

{% block heading %}首頁{% endblock %}

{% block content %}
<h2>Django say -- Hello World !</h2>
    {% comment %} <p>{{ like }}</p> {% endcomment %}
    {% for i in like %}
        {% if i < 5 %}
            <p style='color: red;'>{{ i }}</p>
        {% else %}
            <p style='color: blue;'>{{ i }}</p>
        {% endif %}
        {% if forloop.last %}
            <p>Loop End.</p>
        {% endif %}
        
    {% endfor %}
{% endblock %}

pages/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>亞洲大學 空氣品質監測中心</title>
</head>

<body
    style="background-image: linear-gradient(rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.5)),
url(../../static/admin/img/sky-cloud.jpg);background-repeat: no-repeat;background-attachment: fixed;background-size: cover;">
    <!-- there will be replaced -->
    <div class="jumbotron text-center">
        <h1>亞洲大學 空氣品質監測中心</h1>
        <p>歡迎來到 亞洲大學 空氣品質監測中心</p>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-1">
            </div>
            {% include 'container.html' %}
            <div class="col-sm-1">
            </div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

pages/templates/container.html
<div class="col-sm-10" style="background-color: rgba(255, 255, 255, 0.5);min-height: 1000px;">
    {% block content %}    
    <!-- <h3>主要資訊</h3>
    <p>Lorem ipsum dolor..</p> -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3">
                <p>ASIA airbox 01</p>
            </div>
            <div class="col-sm-3">
                <p>ASIA airbox 02</p>
            </div>
            <div class="col-sm-3">
                <p>ASIA airbox 03</p>
            </div>
            <div class="col-sm-3">
                <p>More Info ...</p>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3 text-center">
                <p>Site Name</p>
            </div>
            <div class="col-sm-4 text-center">
                <p>Last Update Time</p>
            </div>
            <div class="col-sm-5 text-center">
                <p>Activity Suggestion</p>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                RealTime PM2.5
            </div>
            <div class="col-sm-4">
                Realtime Temperature
            </div>
            <div class="col-sm-4">
                Realtime Humidity
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                Last 12 hours PM2.5
            </div>
            <div class="col-sm-4">
                Last 12 hours Temperature
            </div>
            <div class="col-sm-4">
                Last 12 hours Humidity
            </div>
        </div>
    </div>
    {% endblock %}
</div>